### ISSUE TITLE
Transaction Authorization using Credential Presentations

### ISSUE THREAD

**Issue by tlodderstedt** [openid/OpenID4VP#156]
In EUDI Wallet context, we frequently hear the requirement to authorize transactions (electronic signatures and payments) with the wallet. At OSW, a couple of us discussed the idea to make that an extension of a credential presentation. The basic idea is to send transaction data with the presentation request, eg the document to be signed, which causes the wallet to show this data to the user and gather consent. If the user consents, the data is added to the signed credential presentation.

**Comment by Sakurann** [comment]
The concrete proposal is here: https://docs.google.com/document/d/15fdVPBVi6t4CIHk-MiPVBQ4gyherNijt/edit

**Comment by Sakurann** [comment]
Here is the first draft of the proposal: https://docs.google.com/document/d/1E_UlB3fh9zbWiPrzFThEnt69hYN60CWk/edit

**Comment by jogu** [comment]
@ve7jtb said this might have implications on verifier requiring additional trust in the wallet rendering the document/payment info. and might have implications on how issuer implies credential can be used to authorise payment/QES transaction

**Comment by selfissued** [comment]
How does this relate to the Dynamic Credential Request feature of OpenID4VCI at https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0-13.html#name-dynamic-credential-request ?  Both use presentations to authorize actions in progress.

**Comment by Sakurann** [comment]
in-person WG discussion:
- a lot of interest in using this mechanism for payments too (@Sakurann to add payments example to the proposal gdoc)
- overall no objection to the problem statement
- discussion needed where to put transaction_data in the request when multiple credentials can satisfy the request.

**Comment by RByers** [comment]
Here's some references for the context I gave in the meeting for why I argued this was potentially extremely important for payments ecosystem:
 - With tracking (including fingerprinting) being clamped down on in browsers, payments providers are finding it increasingly difficult to mitigate fraud risk.
 - W3C Web Payments Working group has worked for years to try to address this issue with a WebAuthn and Payment Request extension called [Secure Payment Confirmation](https://w3c.github.io/secure-payment-confirmation/), which has been integrated into the 3D Secure specification.
 - [Chrome has supported this API](https://developer.chrome.com/docs/payments/secure-payment-confirmation) and [despite experimental results showing 7pp conversion uplift](https://www.w3.org/2023/Talks/stripe-spc-20230911.pdf), Chrome has not seen much adoption for two primary reasons:
   - WebAuthn implementations have has been reluctant to provide the [device-binding and attestation signals](https://w3c.github.io/webauthn/#sctn-supplemental-public-keys-extension) which would be necessary to satisfy regulations like [PSD2 SCA](https://www.adyen.com/knowledge-hub/psd2-understanding-strong-customer-authentication) (critical in EU)
   - For years Secure Payment Confirmation has been supported only in Chromium-based browsers, with [no indication of support](https://github.com/WebKit/standards-positions/issues/30#issuecomment-1178361664) from the WebKit engine which is required to be used by all browsers on iOS

It seems inevitable to me that the EUDI infrastructure (including the [Digital Credential API](https://github.com/WICG/digital-identities/blob/main/explainer.md)) will be used to satisfy this high-importance use case. Adding direct support to OID4VC makes sense to me. Perhaps we can work with the Web Payments Working Group to re-use existing work here, like sharing the data format for transaction details?

**Comment by awoie** [comment]
> in-person WG discussion:
> 
> * a lot of interest in using this mechanism for payments too (@Sakurann to add payments example to the proposal gdoc)
> * overall no objection to the problem statement
> * discussion needed where to put transaction_data in the request when multiple credentials can satisfy the request.

Just to keep in mind that we will probably also need to think about how to feed transaction_data into the verifiable presentations (i.e. KB-JWT, DeviceResponse or SessionTranscript). Should be no problem but we have to define that.

**Comment by ianbjacobs** [comment]
@RByers thank you for the SPC call-out! See also the draft proposal for a [Revised txAuthSimple extension](https://github.com/w3c/webauthn/issues/2022)

**Comment by hisgarden** [comment]
@RByers @ianbjacobs : This is a great collaboration opportunities among OpenID4VP, W3C and FIDO, as FIDO UAF WG has been advocating Transaction Confirmation capabilities on browser, as referenced in this [FIDO Transaction Confirmation White Paper](https://fidoalliance.org/wp-content/uploads/2020/08/FIDO-Alliance-Transaction-Confirmation-White-Paper-08-18-DM.pdf),  published in Aug 2020: It provides an overview on Transaction Confirmation and the drivers for its support including: regulatory requirements (PSD2, eIDAS); addressing friendly and mobile fraud; and to enable online binding agreements. It explains current approaches for Transaction Confirmation, including through FIDO protocols for native applications, and the value of adding support for it directly in web browsers. It concludes with a call for feedback from relying parties on whether they would like to see Transaction Confirmation should be supported directly in web browsers.  The https://github.com/w3c/webauthn/issues/2022 is based on the implementation done on the native mobile app using [FIDO Universal Authentication Framework (UAF)](https://fidoalliance.org/specs/fido-uaf-v1.2-ps-20201020/fido-uaf-overview-v1.2-ps-20201020.html). For more technical details, please contact Rolf Lindemann [@rlin1](https://github.com/rlin1)

**Comment by bc-pi** [comment]
Consider having the type in this context be more collision resistant or formalized than in RAR.

**Comment by selfissued** [comment]
I support defining this functionality.  I made several suggestions in the document on how to better align the data formats used with other choices made in our protocols.

**Comment by Sakurann** [comment]
for those with the expertise in payment confirmation use-case, I took a look at secure payment confirmation w3c document and are PaymentCurrencyAmount total/currency and PaymentCredentialInstrument the main two parameters that need to be present in the request? So are there any specific concerns with the following structure of the payment_confirmation type of transaction data?:

```
"instructedAmount": {
      "currency": "EUR",
      "amount": "123.50"
   },
   "creditorName": "Merchant A",
   "creditorAccount": {
      "bic":"ABCIDEFFXXX",
      "iban": "DE02100100109307118603"
   },
   "remittanceInformationUnstructured": "Ref Number Merchant"
```

**Comment by OR13** [comment]
Wallet presents encryption keys along with credentials? 
Verifier processes presentation, and encrypts confidential response details to the wallet, to protect against platform layer evesdroppers?

**Comment by selfissued** [comment]
I agree that we want to prioritize being able to perform transaction conformations.  I have two comments about the mechanisms proposed in the first draft:

1. We are not payment schema experts.  Therefore, we should not invent payment schemas and put them into our specification.  Rather, we should recommend the use of payment schemas developed by payment experts.  Talking to some actual payment experts, they caution me that even if we were to come up with a perfect payment schema today, it would be out of date in a year, as new payment and interchange modalities and regulations unfold.  Rather than spending our time inventing a schema, we should spend our time researching and recommending payment schemas that are being actively maintained by experts in that industry.
2. Our specification should use a consistent set of conventions and mechanisms.  Those employed by the https://cloudsignatureconsortium.org/wp-content/uploads/2023/04/csc-api-v2.0.0.2.pdf are quite different than those employed by OAuth and OpenID specs.  A needless difference, for instance is the use of base64 rather than base64url encoding of data.  And the use of OIDs outside of X.509 certificates is also very strange.  Let's use consistent conventions in our spec, rather ones borrowed from unaligned specifications.

**Comment by Sakurann** [comment]
there is a WG consensus to work on the transaction data and prioritize this item, because that transaction data helps multiple use-cases and solves some particular problems.

Closing this issue since agreed to continue brushing up the mechanism in the separate issues: #168, #172, #173 and #174 (and future new ones on this topic)

**Comment by cyberphone** [comment]
@Sakurann @selfissued There is no need to involve "schemes" in a user authorization request; this part should be handled in the next step based on returned payment method (derived from the selected credential).  That is, the wallet does not have to know anything about payment schemes.  By deferring "schemes" you also get away from having to specify creditor (merchant) account details in the request which is good since this may also depend on used "scheme".
Also see: https://www.w3.org/TR/payment-request/

**Comment by Sakurann** [comment]
please continue payment specific discussion in issues dedicated to those (there are multiple)
