### ISSUE TITLE
Where is the mdoc profile specified

### ISSUE THREAD

**Issue by martijnharing** [openid/OpenID4VP#327]
In the DCP working group call it was mentioned that a decision should be made whether the mdoc profile is defined in the OpenID4VP specification or the HAIP specification.

**Comment by Sakurann** [comment]
I opened an issue in HAIP https://github.com/openid/oid4vc-haip-sd-jwt-vc/issues/121, but basically, I think we were wrong to consider defining mdoc profile of OID4VP over the browser API in OID4VP. Because I think the requirement for such profile is to mandate things (like session transcript, response encryption, etc.) to achieve interoperability, and if we do this profile in OID4VP we cannot mandate those things.

**Comment by Sakurann** [comment]
agreed by the WG to specify it in HAIP. minutes: https://lists.openid.net/pipermail/openid-specs-digital-credentials-protocols/Week-of-Mon-20241118/000541.html
