### ISSUE TITLE
Advanced flow for OpenID4VP

### ISSUE THREAD

**Issue by OIDF-automation** [openid/OpenID4VP#45]
### Original Reporter: tlodderstedt

The current cross device flow works fine, however it forces the RP to make assumptions about the SIOP/wallet the user might choose to process the SIOP request. 

I propose to investigate an advanced flow that involves an advertisement/discovery step and allows Rp and SIOP to better adjust the flow to each others capabilities. 

The RP could render a QR code that give rise to its capabilities and endpoints. The user then scans that QR code with the wallet of her choice. 

The wallet uses the QR code data and send a request to the RP containing its capabilities and endpoints/identifiers in a direct HTTPS POST request.

In the HTTPS POST response, the RP directly sends with the authentication request data \(tailored for the particular SIOP\). 

As already noted, this flow would allow the RP and the SIOP to tailor the requests to each others capabilities. Also, the QR code could potentially be static and concise.

**Comment by Sakurann** [comment]
at OSW we discussed an alternative approach, which builds up on RFC9101 (passing request by reference):
1) verifier sends an authorization request with a request_uri to the wallet (custom url scheme, etc.)
2) when the wallet obtains the request object at a received request_uri, it sends a POST request with the parameters describing wallet capabilities, maybe wallet attestation etc.
3) flow continues

but I prefer @tlodderstedt 's proposal[ in this comment](https://github.com/openid/OpenID4VP/issues/45#issuecomment-1707474498), mainly because:
- it addresses the wallet invocation problem because verifier advertisement (to borrow Torsten's terms) might use a custom url scheme, but the actual authorization request that matters can be tailored to a wallet specific endpoint (app link/universal link)
-  is cleaner than building up on rfc9101.

**Comment by Sakurann** [comment]
@alenhorvat thank you - I am trying to better understand the flow you linked to: does the flow you point to work only when the wallet initiates the flow? is the assumption that the wallet knows verifier endpoint out of band? how does cross device flow look like? why is there token request from the wallet - what is access token scoped for? why does the description text talk about credential req-res if this is about presentation? Is the Self-issued ID Token of the wallet sent in the first authorize request to the verifier without verifier provided nonce?

**Comment by alenhorvat** [comment]
I believe there are 2 possible scenarios
a) dynamic wallet discovery - in this case a simple POST to an ?authorisation? endpoint with wallet metadata could solve the problem (same behaviour as redirect_uri except that it can accept the wallet metadata and adjust the request object accordingly)
b) verifier requires additional info - here the VP flow can be re-used as described above.

Essentially there can be two scenarios
a) VP flow embedded into another VP flow
b) 2 sequential VP flows (this is essentially what @tlodderstedt  described)

**Comment by alenhorvat** [comment]
Hi @Sakurann. We elaborated the flow EBSI designed and adjusted the terminology to the proposal of @tlodderstedt 
https://api-test.ebsi.eu/docs/ct/verification-offering

I hope this answers (some of) your questions.

**Comment by peppelinux** [comment]
> 

Providing the WIA during the presentation phase, better if before obtaining the signed request object, we have the following benefits:

- providing wallet instance metadata/capabilities to the RP
- providing the reliability of the wallet instance and its status, if revoked or not
- avoiding the requirement of chained revocation: even if a PID is still valid without any valid wallet instance attestation the wallet instance cannot present credentials. Then if a wallet solution revoke a wallet instance this won't affect the credentials already issued to that instance
- giving the PoP of a private key to be used for the signature of the id_token within the SIOP flow, where a pseudonym MUST carry the assurance about the reliability of its issuer, the wallet instance

**Comment by peppelinux** [comment]
considering also that there are cases where the wallet instance acts like a verifier that requests a presentation, or obtains a presentation offer, to/from another wallet instance, the sole trust to be established between the actors is the WIA, since the wallet instance is not an organizative entity with a publick endpoint where to publish its metadata/keys (while the wallet provider, that's the WIA issuer, has it)

side note:
We may assume that the verifier_attestation we have in OpenID4VP SHOULD allow multiple `typ` allowing that the attestation may be of different type (issue here: https://github.com/openid/OpenID4VP/issues/32)

**Comment by Sakurann** [comment]
btw Issue #47 mentions another mechanism to discover wallet metadata - using service nedpoint from the wallet's DID Doc

**Comment by alenhorvat** [comment]
@Sakurann, to use that mechanism the wallet needs to communicate it's DID, first. It boils down to the "dynamic wallet metadata discovery" we're discussing here.

**Comment by David-Chadwick** [comment]
@tlodderstedt It would be good if you could upload your swim lane for your proposed message flow for this issue that you showed to us in the meeting of 7 Sept 2023.
WRT to that flow, my concern is that the assumption is that the wallet trusts the verifier and is prepared to send information to the verifier before knowing if the verifier is who they say they are, or can be trusted. Thus the first message from the verifier to the wallet should allow the wallet to determine if the verifier is trustworthy (or not). This can be achieved by the verifier saying "this is me", which can be a true or false statement, it does not matter since the wallet will verify this. (Therefore the verifier's message does not need to be signed). It the wallet determines that 'this is me' is trustworthy it should be able to collect sufficient meta information about the verifier in order to continue the dialogue, without any further direct interaction with the verifier e.g. by going to a well known place for 'this is me' to retrieve the meta-data.
In the WG call of 7 Sept @tlodderstedt raised the issue that although my proposed solution works if both the verifier and wallet are in the same trust domain, it does not work if they are not in the same trust domain. However this is not true. It is possible for the verifier and wallet to be in different trust domains but if they share a common trust protocol they can still determine the other's trustworthiness. (This is how X.509 and TRAIN works for example.) Furthermore, the OIDF GAIN POC WG is developing a solution for cross domain trust where the entities are in different trust domains and use different trust protocols as well (by using OID Federation as the common bridging protocol). So we should leverage the GAIN work and incorporate the GAIN message(s) into the initial dialogue between the verifier and wallet, and then any wallet will be able to determine the trustworthiness of any verifier (and vice versa) providing they both either support GAIN or the same (possibly proprietary) protocol.

**Comment by peppelinux** [comment]
I read diligently the entire thread.

Is there any concrete reason for not extending the request_uri endpoint with a POST http method that would allow us to use rfc7521 to pass the wallet attestation? 

Alternative to rfc7521 already implemented in Italy: we use dpop in the RP request_uri to provide the wallet attestation with a proof of possession.

We have decided dpop because It is very simple and doesn't require the http post method.

However this doesn't solve the problem for wallet 2 wallet interactions, probably It would be Better to define a new specialized endpoint/URL-scheme to enable the provisioning of the wallet attestation.

This increases complexity.

The concept of the presentation offer gives us a way to provide the wallet attestation. The wallet instance presents itself to an RP and this latter has to uniquely identify the wallet instance to know which request forge for It later on, within the request uri endpoint. This sounds like a kind of wallet registration to the RP, that could be made even without complete the presentation phase. Something that lives by its own.

Before going ahead we should care about the risks that this feature May be exploited to collect wallet attestations by RP without any scope related to the presentation. -> this would be possible Aldo with dpop/rfc7521/any-other.

By extending the request_uri endpoint we restrict the scope of the request for the provisioning of the signed request, for the same scope and withing the same request the wallet provides the attestation (dpop in http get or rfc7521 with http post) according to the italian approach.

I'm not excluding the advertisement endpoint, I'm Just wondering about the impacts of that and I look forward to work more on this with you.

**Comment by mtaimela** [comment]
There's two protocols: Issuance and Presentation. The problem below is solved in the issuance side (VCI).
> ..however it forces the RP to make assumptions about the SIOP/wallet the user might choose to process the SIOP request.

The key for the introduction is the `XXX Offer` and client driven discovery. I think it is important to keep these two specs symmetrical, so if the problem also requires "wallet to wallet issuance and presentation", then the Offer(s) should be amended with the metadata for the discovery and possibly a signature to protect the metadata.

Why Presentation should not adopt the Offer pattern? This pattern works and exists in Issuance side. If you would not like to introduce Presentation side Offer, please remove it from the Issuance too

**Comment by peppelinux** [comment]
@mtaimela your proposal makes sense, it would be better make VCI and VP similar

**Comment by tlodderstedt** [comment]
@mtaimela the proposal I made uses the same pattern as the credential offer. 
@peppelinux where do you see a difference?

Please find attached the sequence diagram I used yesterday to illustrate the idea.

![image](https://github.com/openid/OpenID4VP/assets/328358/6dc7ee74-c84f-4727-8e0f-bf29147af2e2)

**Comment by fbaud** [comment]
Hi @tlodderstedt,

We did implement a workflow that is close to your sequence diagram, but with some differences due to our particular architecture.

We have:

- a data server that may be equivalent to the verifier backend in your diagram if I understand it correctly. But in our case it is belonging to a different organisation (hence some of my remarks below)
- a wordpress widget that is the user agent but that is configured by simple short_code attributes (by a non programmer)
- a SaaS server that is taking care of the verifier role
- a wallet that we would like to use standard calls

Now for the differences:

- we don't want the wallet to contact the backend but only the verifier
- verifier is making the mediation between the widget, the wallet and the backend/data server
- user must be able to submit a presentation from their wallet without authenticating to the verifier if the widget defines it accepts all presentations
- if the widget defines an authentication/authorisation scheme for the submission, the wallet will get the requirement with call number 6
- we don't have response number 11 (I'm not sure how the wallet can reach the user agent, and maybe it is part of my confusion when I imagine that the user agent can be a wordpress widget). We do have some websocket exchange of information but it is intermediated by the verifier and is not taking part to the workflow

All in all, we have definitely adopted a sequence for presentation separate from the issuance, even if very similar for the steps 1 to 4. And we strongly support having a distinct specification from issuance

We do support what we call dynamic bootstrap like the one in your sequence diagram, or static bootstrap (user agent produces a qr code as a gif without ever contacting the verifier). We can support the 2 modes thanks to number 4 call, but definitely need to have a transactionId AND verifier_state to be passed all along to let the verifier mimic the rest of the workflow

**Comment by peppelinux** [comment]
@tlodderstedt 

the difference is the semantic, offer != advertisement.
I have worked on a similar approach, where:

1. advertisement endpoint is called pre-request-uri-endpoint
2. in this pre-request-uri-endpoint I detect if the device is mobile or desktop, then I decide if return a QRCode or a Redirect, then I create the session (with state, nonce, cookie bindings and so on) and return the Response, something like this

````
HTTP/1.1 /pre-authz-endpoint Found
Location: https://wallet-provider.eudi.wallet.gov.it?
client_id=https%3A%2F%2Frelying-party.example.org%2Fcb
&request_uri=https%3A%2F%2Frelying-party.example.org%2Frequest_uri%3Fid%3Drandom-value
````
3. why `transaction-id` exists wouldn't `state` be enough?
4. number 5 -> why the wallet creates a presentation request, wouldn't be the RP to create that? It's just a semantic issue that confuses minds, we may just mention "request_uri endpoint", since it is the RP that requests a presentation while in this step the wallet instance just fetches the signed request

For now the most relevant question would be HOW the wallet can provide the wallet attestation to the request_uri endpoint?
DPoP or RFC7521 or any alternative?

Then when I read `an ephemeral key - to be used to encrypt the authorization request` I assume that the wallet attestation must contain at least a public key, is then this ephemeral key really required?

**Comment by fbaud** [comment]
@tlodderstedt @peppelinux ,

While on the semantic side, here are my own bias:

>> offer != advertisement.
we call it a credential-call to distinguish from a credential-offer. Beyond the semantic, I believe that the pull vs push has some implication on the design and authorisations. That is the reason I believe the 2 workflows should be separated

>> 1 advertisement endpoint is called pre-request-uri-endpoint
we also distinguish between the pre-request part, which is an exchange between our widget and the verifier. But we should be able also to bootstrap without a pre-request in what we called the static bootstrap (e.g. gif sent by email)

>> 2 in this pre-request-uri-endpoint I detect if the device is mobile or desktop
This is where we have a very different situation. The user agent is a widget, and it is its business logic that decides everything concerning the bootstrap, in particular what it is asking the wallet to provide and what the verifier server should know to complete the workflow

>> 3 why transaction-id exists wouldn't state be enough?
It should be enough. But we also pass the 2 because we want to be able to recreate a state from the transaction-id in case the state disappeared on the server (failback procedures).
Actually we call the transation-id a credentialCallId

>> 4 number 5 -> why the wallet creates a presentation request
My understanding was that number 5 was a call for the verifier to create a presentation request, which is what we do in our implementation. But to be more specific, in our case, the verifier server is creating a request based on the instructions explicited by the widget (with potential additonal elements mainly related to the security policy of the verifier server).

**Comment by fbaud** [comment]
Hi @alenhorvat 

It seems I'm not able to open the document at https://api-test.ebsi.eu/docs/ct/verification-offering

**Comment by alenhorvat** [comment]
drafts/oid4vp-presentation-offer.md · ebip/oid4vp-presentation-offer · EBSI / Ecosystem · GitLabcode.europa.euAlen HorvatOn 9 Sep 2023, at 08:12, Frederic Baud ***@***.***> wrote:﻿
Hi @alenhorvat
It seems I'm not able to open the document at https://api-test.ebsi.eu/docs/ct/verification-offering

**Comment by alenhorvat** [comment]
https://code.europa.eu/ebsi/ecosystem/-/blob/ebip/oid4vp-presentation-offer/drafts/oid4vp-presentation-offer.md

**Comment by Sakurann** [comment]
@peppelinux do you mean [RFC9101 (RAR)](https://datatracker.ietf.org/doc/html/rfc9101).

I think that's the proposal I made [here](https://github.com/openid/OpenID4VP/issues/45#issuecomment-1707665070), but I am not in its favor because i think Torsten's proposal is cleaner in terms of separating what verifier sends before//after it knows wallet capabilities/attestations..

also I do not think reusing DPoP is a good idea for various reasons because it reuses somehting meant for other purposes, so for example it would mean stuffing extra claims expressing wallet capabilities in DPoP JWT

**Comment by tlodderstedt** [comment]
> Regarding the diagram, I think this will definitely work. It also looks like that the "Presentation Flow" is not yet discovered, just the means of transferring VCs is (transport envelope with DIFv2).

This sequence diagram describes how to request and present a presentation of one or more credentials (OID4VP). It will also be able to cover SIOP v2 (as it only adds another pre-step before the actual authorization request is passed from the verifier to the wallet), i.e. the request object in step 6 would also contain SIOP v2 parameters, like a scope "openid".

**Comment by peppelinux** [comment]
> @peppelinux do you mean [RFC9101 (RAR)](https://datatracker.ietf.org/doc/html/rfc9101).

Not sure I meant RAR but I fully agree with you to have a specialized endpoint for handling the wallet instance authentication with a verifiable attestation (WIA) instead of pushing it to an endpoint that was intended for other scopes (request_uri)

the flow we have implemented aims to give a wallet verifiable metadata discovery to the RP, when this issues will reach an actionable conslusion then implementing the endpoint would be the way to go

**Comment by peppelinux** [comment]
@tlodderstedt before giving the conclusions and the agreements within this thread, could you please answers or give any hints to files the points raised here https://github.com/openid/OpenID4VP/issues/45#issuecomment-1712357096

**Comment by peppelinux** [comment]
another though

We have discussed about the value of having a specialized endpoint for doing the wallet discovery, since we need it in both presentation and issuance phase

having a special purpose endpoint, reusable, it could be used also for wallet2wallet presentations, using custom url schemas

other kind of relations may happen, like wallet2RS (authentic sources, and so on). A basic component, avulsed by the context and then usable in multiple contexts

**Comment by mtaimela** [comment]
@peppelinux 
> We have discussed about the value of having a specialized endpoint for doing the wallet discovery, since we need it in both presentation and issuance phase

The text leaves room for two specialised endpoints or for one unified. In general, I would prefer not to have multiple endpoints for a single application. The problem lies in mobile configurations as you may register the default endpoints to different apps, which will cause usability issues. Single scheme or Universal Links/App link is better as parameters or values can handle the behavioural split. I'm referring to VCI and VP invocation mechanisms.

**Comment by peppelinux** [comment]
In the following issues I would like to explore with you how we may get a proper generalization of oauth-attestation-based-client-auth to design the nonce endpoint as a protected endpoint and give a good harmonization in both OpenID4VCI and OpenID4VP (within this issue)

https://github.com/vcstuff/draft-ietf-oauth-attestation-based-client-auth/issues/46

@tlodderstedt WDYT?

**Comment by tlodderstedt** [comment]
I would like to get the design of the flow for OpenID4VP straight before we discuss harmonization.

**Comment by tlodderstedt** [comment]
Here is the PR for this issue: https://github.com/openid/OpenID4VP/pull/52

**Comment by peppelinux** [comment]
An alternative flow was provided here: https://github.com/openid/OpenID4VP/pull/52#issuecomment-1741179550

please provide your reactions/comments if any

**Comment by tlodderstedt** [comment]
Hi all, I filed a new PR with an alternative design for the advanced flow. It is less sophisticated but simpler and more privacy preserving. I hope it can be the basis of a consensus. Have a look at PR #59.

**Comment by Sakurann** [comment]
PR merged
